# docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    container_name: skyeng_postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
#    healthcheck:
#       test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}" ]
#       interval: 5s
#       timeout: 10s
#       retries: 5
#       start_period: 10s
#    volumes:
#      - ./db:/var/lib/postgresql/data


networks:
  default:
      name: lan_fastapi
